// The service worker, served at /sw.js (root scope).
//
// It's generated by a static route instead of living in public/ so each deploy
// gets a unique version: on Vercel that's the deployment ID, so a new deploy
// installs a fresh worker and deletes the previous deploy's caches.
//
// Caching rules:
// - Only same-origin GET requests are handled. Server Actions (POST), PayPal,
//   Google, and the Vercel toolbar are never touched.
// - Pages and RSC payloads: network first (always the current deploy when
//   online), cached copy when offline, then the offline page.
// - /_next/static (content-hashed, immutable): cache first.
// - Images and icons: stale-while-revalidate.
// - Videos and range requests: never cached (they're tens of MB).

import { buildServiceWorker, SW_VERSION } from '@/lib/pwa/service-worker';

export const dynamic = 'force-static';

export function GET() {
  return new Response(buildServiceWorker(SW_VERSION), {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Browsers must always re-check the worker so new deploys roll out.
      'Cache-Control': 'no-cache, no-store, must-revalidate',
    },
  });
}
